### ISSUE TITLE
Remove Wii Mod Lite

### ISSUE THREAD

**Issue by emilydaemon** [OpenShopChannel/Apps#23]
A lengthy discussion about Wii Mod Lite and why it is bad has gone on here: https://github.com/RiiConnect24/Wii-Guide/pull/360

**Comment by Artuto** [comment]
I don't see a concrete reason why Wii Mod Lite "has gone bad".

Users installing the wrong System Menu version for their systems is their responsibility.

We are not here to correct user error, this is an app repository where both apps can co-exist and users can choose which one they want to use.

Unless the app does something malicious on purpose, I don't see why we should remove it.

**Comment by DardelHMB** [comment]
Wii Mod Lite has always been bad.

As mentioned in the PR emily linked, it lacks important safety checks that yawmME has that prevent a bad system menu from being installed.

The tool is also closed source, we have no way of contacting the author. By being closed source, it is also ILLEGAL since it breaks the GPL, since the tool is a fork of Wii Mod and uses code from lots of different programs, like Waninkoko's WAD Manager 1.7, which is licensed under GPL.

**Comment by playerjmr** [comment]
Not to mention, it has issues with freezing when deleting certain titles, and also freezing when navigating too many menus. Generally it isn’t a good idea to include those multitools inside of what is supposed to be a wad manager anyway, especially in particular the region changer. People who don’t know what they are doing can really mess up their Wii like that.

**Comment by GabubuAvailable** [comment]
In short we need to remove it... WML caused lots of problems and these are specified here by the others.
> Users installing the wrong System Menu version for their systems is their responsibility.
It's true but you see, WML doesn't even warn you about that, while YAWMME does.

**Comment by playerjmr** [comment]
> Users installing the wrong System Menu version for their systems is their responsibility.
> 
> We are not here to correct user error, this is an app repository where both apps can co-exist and users can choose which one they want to use.

By this logic KoreanKii should be added back as well.

**Comment by vgmoose** [comment]
Hi! I'm chiming in because this issue came up when discussing using OSC API for the [hb-appstore](https://github.com/fortheusers/hb-appstore) project. I'm also in favor of the removal, or seeking license clarification.

For:
> I don't see a concrete reason why Wii Mod Lite "has gone bad".

This seems notable:
> [T]he tool is a fork of Wii Mod and uses code from lots of different programs, like Waninkoko's WAD Manager 1.7, which is licensed under GPL.

If the app isn't complying with GPL (where redistributing the full source code is one of the sublicense requirements), then it's infringing on the copyright of the original authors of those projects.

This might not be an issue for the author of WML in the context where it was originally distributed (for example if China has more relaxed copyright laws). However, it would still be an issue when redistributing it outside of that context.

From the [other discussion](https://github.com/RiiConnect24/Wii-Guide/pull/360#issuecomment-1624501244) on this:
> [T]he Lite version was made by a person in China, I believe that it breaks the GPL license because the author didn't share its code.

That's true! But "breaks the GPL" in this context means "violates the terms of the license", which is a copyright infringement.  I don't think it's hyperbole to say that you could use that same line of reasoning to justify redistributing retail Wii games, as long as a Chinese user modified it first.

**Comment by KokiKitsune2007** [comment]
NGL I was a little suspicious when I couldn't find Wii Mod Lite's source code.

**Comment by DardelHMB** [comment]
Will it be removed or not? 
If not, I (among many others) would like to hear your reasoning behind it. I see no reason why it should be on the Open Shop Channel.

**Comment by KokiKitsune2007** [comment]
Lol, I forgot about this topic but Idk, All I know is I found the original source code for WiiMod (the original app before WiiMod lite).  Jskyboo licensed it under GPL 3.0.

**Comment by korbosoft** [comment]
Please do.

**Comment by KokiKitsune2007** [comment]
https://archive.org/details/wiimod

**Comment by KokiKitsune2007** [comment]
You can tell it's old because it doesn't have the "apply patches please wait.." screen.

**Comment by playerjmr** [comment]
> One more thing, we don't know if kkline38 is violating gpl. I mean he might've asked Jskyboo to grant him an exception with making it closed source privately. Someone might have to ask him if he granted KKline38 permission.

if an exception was granted, don’t you think he wouldn’t have avoided being contacted if there was? Anyway it still doesn’t matter because regardless the app cannot be updated so it should be removed.

**Comment by korbosoft** [comment]
> We are not here to correct user error
@Artuto Even then, it still, violates the GPL. If you are OK with this, then you are OK with copyright infringement. Please make the right decision.

**Comment by KokiKitsune2007** [comment]
> > One more thing, we don't know if kkline38 is violating gpl. I mean he might've asked Jskyboo to grant him an exception with making it closed source privately. Someone might have to ask him if he granted KKline38 permission.
> 
> if an exception was granted, don’t you think he wouldn’t have avoided being contacted if there was? Anyway it still doesn’t matter because regardless the app cannot be updated so it should be removed.

True, but yeah, I think it might be confirmed that Kkline38 is violating gpl.  Cause Jskyboo licensed WiiMod under gpl 3.0

**Comment by korbosoft** [comment]
At this point it feels like we are just being ignored.

**Comment by KokiKitsune2007** [comment]
> At this point it feels like we are just being ignored.

Same...  I feel like we are

**Comment by DardelHMB** [comment]
@Artuto in case it wasn't clear, we are waiting for your response.

**Comment by Artuto** [comment]
A decision hasn't been made

**Comment by xflak** [comment]
If I'm not too late to the party, I'd like to add that I agree with it's removal. If someone wants to use this brick risk of a tool, let's make it a bit more difficult to find.

**Comment by KokiKitsune2007** [comment]
> If I'm not too late to the party, I'd like to add that I agree with it's removal. If someone wants to use this brick risk of a tool, let's make it a bit more difficult to find.

Yeah, I agree with you XFlak, I mean, it seems WiiMod lite is at least 13 years old lol.  If only kkline38 kept maintaining it and actually followed gpl.

**Comment by korbosoft** [comment]
its been a month.

**Comment by KokiKitsune2007** [comment]
> its been a month.

Did they never say anything or remove it?

**Comment by GriffintheFolf** [comment]
No, not at this point in time.

**Comment by KokiKitsune2007** [comment]
> No, not at this point in time.

Aight, well they better remove it soon.

**Comment by korbosoft** [comment]
> Aight, well they better remove it soon.

If it has taken this long just to make a decision on if they should violate copyright law or not, they probably aren't going to.

**Comment by KokiKitsune2007** [comment]
> > Aight, well they better remove it soon.
> 
> If it has taken this long just to make a decision on if they should violate copyright law or not, they probably aren't going to.

Yeah, probably not lol

**Comment by korbosoft** [comment]
@Artuto I'm not sure what there is to decide. Wii Mod Lite violates copyright law, which means if the creator of Wii Mod, who is seemingly still on the internet to this very day, wanted to, they would be able to wipe this entire repository off of github if you didn't comply.

**Comment by KokiKitsune2007** [comment]
> @Artuto I'm not sure what there is to decide. Wii Mod Lite violates copyright law, which means if the creator of Wii Mod, who is seemingly still on the internet to this very day, wanted to, they would be able to wipe this entire repository off of GitHub if you didn't comply.

I'm honestly surprised that jskyboo is not taking action.  It might be because he gave the creator of wii mod lite permission to keep it closed source.  I mean look at riivolution, it uses libwiigui and it is open source but riivolution is not.  They didn't violate anything because the riivolution team ask tantric if they can make it closed source.

https://gbatemp.net/threads/riivolution-violates-gnu-gpl.252764/

**Comment by playerjmr** [comment]
> > @Artuto I'm not sure what there is to decide. Wii Mod Lite violates copyright law, which means if the creator of Wii Mod, who is seemingly still on the internet to this very day, wanted to, they would be able to wipe this entire repository off of GitHub if you didn't comply.
> 
> I'm honestly surprised that jskyboo is not taking action. It might be because he gave the creator of wii mod lite permission to keep it closed source. I mean look at riivolution, it uses libwiigui and it is open source but riivolution is not. They didn't violate anything because the riivolution team ask tantric if they can make it closed source.
> 
> https://gbatemp.net/threads/riivolution-violates-gnu-gpl.252764/

Riivolution is actually open source and the code can be found at ArielX/rawksd. That’s an outdated gbatemp thread

**Comment by KokiKitsune2007** [comment]
> > > @Artuto I'm not sure what there is to decide. Wii Mod Lite violates copyright law, which means if the creator of Wii Mod, who is seemingly still on the internet to this very day, wanted to, they would be able to wipe this entire repository off of GitHub if you didn't comply.
> > 
> > 
> > I'm honestly surprised that jskyboo is not taking action. It might be because he gave the creator of wii mod lite permission to keep it closed source. I mean look at riivolution, it uses libwiigui and it is open source but riivolution is not. They didn't violate anything because the riivolution team ask tantric if they can make it closed source.
> > https://gbatemp.net/threads/riivolution-violates-gnu-gpl.252764/
> 
> Riivolution is actually open source and the code can be found at ArielX/rawksd. That’s an outdated gbatemp thread

Oh, ok.

**Comment by Artuto** [comment]
After consideration of all the arguments provided in this thread, and internal discussion with the other team members, the following has been decided:

1. Due to the lack of feasible alternatives for some features, like title deleting, a notice will be placed on the WML page in the library stating that its use is discouraged, and that more modern alternatives should be used where possible.
2. Regarding the license, we have concluded that we do not have all the elements necessary to say that the license is being broken with malicious intent, as such, we will not be removing the app.

We will always honor copyright takedown requests coming from the original copyright holder via our support email (support [at] oscwii.org), and this is in no way opening the doors to apps that do break the license in malicious manners.
